### ISSUE TITLE
Request to Add display light toggle command And Energy consumption.

### ISSUE THREAD

**Issue by sparsh308** [rkzofficial/miraie-ac#1]
Hi, my name is Sparsh Kishore and I am impressed by this integration want to collaborate in the future for Panasonic Mirai AC integration,

if possible I will try to add that toggle command and make a pull request for that. 
Also will try to contribute by  Adding a nice login page

also if possible please include energy consumption

**Comment by rkzofficial** [comment]
Hi @sparsh308 display light toggle has been added by @ankitduseja, we should close this issue now and for the Energy consumption please create a new issue separately.

Thanks.
