### ISSUE TITLE
Please do see if Heat mode can be added. 

### ISSUE THREAD

**Issue by vishuraogithub** [rkzofficial/miraie-ac#3]
https://github.com/rkzofficial/miraie-ac/blob/72d53e1999518a83f83f49e600a5f4d28092d447/miraie_ac/enums.py#L21

There is a display off command as well, i have to route that through IR, can you add that too in some way?

**Comment by vishuraogithub** [comment]
I am coming from the Homeassistant domain, seems home assistant cant expose display turning off.

**Comment by deCodeIt** [comment]
Yes, Home Assistant doesn't support turning on/off display.
A hacky way can be to use `presets` to toggle the display.

@rkzofficial You can close this issue as it isn't supported by HA.

**Comment by rkzofficial** [comment]
> Yes, Home Assistant doesn't support turning on/off display.
> A hacky way can be to use `presets` to toggle the display.
> 
> @rkzofficial You can close this issue as it isn't supported by HA.

Yes I am aware of this I also thought using presets to support this feature but its not feasible in long run.

Unless we have custom climate card we can't support this feature.

**Comment by rkzofficial** [comment]
@vishuraogithub I will make create a separate issue for creating custom card in home assistant so that we can also support profiles.

So closing this issue for now.
